// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { z } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published Tren Maya Trips blog posts (title, slug, excerpt, category, published date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max posts to return (default 10)."),
    category_slug: z.string().optional().describe("Optional blog category slug to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category_slug }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let q = supabase.from("blog_posts").select("slug,title,excerpt,category_slug,published_at,featured").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (category_slug) q = q.eq("category_slug", category_slug);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z2 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single published blog post (full content) by slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("The blog post slug.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("blog_posts").select("*").eq("status", "published").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published post with slug ${slug}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-destinations.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z3 } from "npm:zod@^4.4.3";
var list_destinations_default = defineTool3({
  name: "list_destinations",
  title: "List destinations",
  description: "List Tren Maya destinations (name, slug, state, short description).",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("destinations").select("*").limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { destinations: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-packages.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z4 } from "npm:zod@^4.4.3";
var list_packages_default = defineTool4({
  name: "list_packages",
  title: "List travel packages",
  description: "List Tren Maya Trips travel packages with pricing and duration.",
  inputSchema: { limit: z4.number().int().min(1).max(100).default(50) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("packages").select("*").limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { packages: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-routes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z5 } from "npm:zod@^4.4.3";
var list_routes_default = defineTool5({
  name: "list_routes",
  title: "List Tren Maya routes",
  description: "List the Tren Maya train routes (origin, destination, duration, highlights).",
  inputSchema: { limit: z5.number().int().min(1).max(100).default(50) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    const { data, error } = await supabase.from("routes").select("*").limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { routes: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-experiences.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z6 } from "npm:zod@^4.4.3";
var list_experiences_default = defineTool6({
  name: "list_experiences",
  title: "List experiences",
  description: "List tours and experiences available along the Tren Maya route.",
  inputSchema: {
    limit: z6.number().int().min(1).max(100).default(50),
    category_slug: z6.string().optional().describe("Optional experience category slug filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category_slug }) => {
    const supabase = createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY);
    let q = supabase.from("experiences").select("*").limit(limit);
    if (category_slug) q = q.eq("category_slug", category_slug);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { experiences: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vvbpzfygfebkjfeeylos";
var mcp_default = defineMcp({
  name: "tren-maya-trips-mcp",
  title: "Tren Maya Trips",
  version: "0.1.0",
  instructions: "Read-only tools for the Tren Maya Trips travel site. Browse published blog posts, destinations, train routes, travel packages, and experiences along the Tren Maya.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_blog_posts_default, get_blog_post_default, list_destinations_default, list_packages_default, list_routes_default, list_experiences_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
